### PR TITLE
Update Appsflyer to 7.11

### PR DESCRIPTION
**Pull request by BrandonStalnaker**

### CODE REVIEW

**Review by samdozor — DISMISSED** [review]
Can you update to AppsFlyer 5.0?

**Comment by BrandonStalnaker** [comment]
@samdozor Do they have a binary release of it? I've not made an attempt any other way. Just curious if you knew. https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/Carthage.json

Edit: Well they do link a new one in their github docs but it still doesn't support 5.0
https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerTracker.json

**Comment by samdozor** [comment]
It looks like they do have a binary release on their releases page, but haven't updated their JSON file. I'd suggest we update to 5.0 regardless of that even if it means we don't support building as a binary, and log an issue on their repo to ask them to update their json.

Also, here's the release notes for 5.0 to look through, it's a major release which is what was driving the request to update to it: https://support.appsflyer.com/hc/en-us/articles/360003090618

**Comment by samdozor** [comment]
Looks like there's a syntax issue somewhere in the travis yaml: https://travis-ci.org/mparticle-integrations/mparticle-apple-integration-appsflyer/requests?requestId=192137736

**Comment by BrandonStalnaker** [comment]
@samdozor Thanks for pointing it out. Seems to be going through now.

**Review by willpassidomo — APPROVED** [review]

**Pull request merged**
